AttributeError: module 'matplotlib' has no attribute 'stem'

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

# create 2D array of table given above
data = [['E001', 'M', 34, 123, 'Normal', 350],
        ['E002', 'F', 40, 114, 'Overweight', 450],
        ['E003', 'F', 37, 135, 'Obesity', 169],
        ['E004', 'M', 30, 139, 'Underweight', 189],
        ['E005', 'F', 70, 117, 'Underweight', 183],
        ['E006', 'M', 36, 121, 'Normal', 80],
        ['E007', 'M', 32, 133, 'Obesity', 166],
        ['E008', 'F', 26, 140, 'Normal', 120],
        ['E009', 'M', 32, 133, 'Normal', 75],
        ['E010', 'M', 36, 133, 'Underweight', 40] ]

# dataframe created with
# the above data array
df = pd.DataFrame(data, columns = ['EMPID', 'Gender','Age', 'Sales','BMI', 'Income'] )

# create histogram for numeric data
df.hist()
# show plot
plt.show()

sum=21.3+20.8+19
mean = sum/3
print(mean)
20.366666666666667
import statistics as st

list1 =[1, 2, 3, 4]
        #  2+3/2 is the median
print(st.median(list1))
2.5
import statistics as st

list1 =[2,3,7,4,2,6,4,7,7,4,7,2,4]       #  2+3/2 is the median
print(st.mode(list1))
7
import statistics as st

list1 =[2,3,7,4,2,6,4,7,7,4,7,2,4]       #  2+3/2 is the median
max1 = max(list1)
min1 = min(list1)
range = max1  - min1
print(range)
5
import statistics as st
list1 =[2.75, 1.75, 1.25, 0.25, 0.5, 1.25, 3.5]
print(st.variance(list1))
1.3720238095238095
import pandas as pd
import matplotlib.pyplot as plt
  
# create 2D array of table given above
data = [['E001', 'M', 34, 123, 'Normal', 50],
        ['E002', 'F', 40, 114, 'Overweight', 150],
        ['E003', 'F', 37, 135, 'Obesity', 169],
        ['E004', 'M', 30, 139, 'Underweight', 210],
        ['E005', 'F', 44, 117, 'Underweight', 183],
        ['E006', 'M', 36, 121, 'Normal', 80],
        ['E007', 'M', 32, 133, 'Obesity', 166],
        ['E008', 'F', 26, 140, 'Normal', 120],
        ['E009', 'M', 32, 133, 'Normal', 75],
        ['E010', 'M', 36, 133, 'Underweight', 40],
        ['E011', 'M', 50, 153, 'Underweight', 123] ]

# dataframe created with
# the above data array
df = pd.DataFrame(data, columns = ['EMPID', 'Gender','Age', 'Sales','BMI', 'Income'] )
df.plot.bar()
plt.show()
plt.bar(df['Age'], df['Income'])
plt.show()
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
g:\Backup Sep 2 2022\Desk\sample\Module3\practical.ipynb Cell 7 in <cell line: 2>()
      <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#W6sZmlsZQ%3D%3D?line=0'>1</a> import pandas as pd
----> <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#W6sZmlsZQ%3D%3D?line=1'>2</a> import matplotlib.pyplot as plt
      <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#W6sZmlsZQ%3D%3D?line=3'>4</a> # create 2D array of table given above
      <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#W6sZmlsZQ%3D%3D?line=4'>5</a> data = [['E001', 'M', 34, 123, 'Normal', 50],
      <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#W6sZmlsZQ%3D%3D?line=5'>6</a>         ['E002', 'F', 40, 114, 'Overweight', 150],
      <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#W6sZmlsZQ%3D%3D?line=6'>7</a>         ['E003', 'F', 37, 135, 'Obesity', 169],
   (...)
     <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#W6sZmlsZQ%3D%3D?line=13'>14</a>         ['E010', 'M', 36, 133, 'Underweight', 40],
     <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#W6sZmlsZQ%3D%3D?line=14'>15</a>         ['E011', 'M', 50, 153, 'Underweight', 123] ]

File c:\ProgramData\Anaconda3\lib\site-packages\matplotlib\pyplot.py:57, in <module>
     55 from matplotlib import docstring
     56 from matplotlib.backend_bases import FigureCanvasBase, MouseButton
---> 57 from matplotlib.figure import Figure, figaspect
     58 from matplotlib.gridspec import GridSpec, SubplotSpec
     59 from matplotlib import rcParams, rcParamsDefault, get_backend, rcParamsOrig

File c:\ProgramData\Anaconda3\lib\site-packages\matplotlib\figure.py:26, in <module>
     24 import matplotlib as mpl
     25 from matplotlib import _blocking_input, docstring, projections
---> 26 from matplotlib.artist import (
     27     Artist, allow_rasterization, _finalize_rasterization)
     28 from matplotlib.backend_bases import (
     29     FigureCanvasBase, NonGuiException, MouseButton, _get_renderer)
     30 import matplotlib._api as _api

ImportError: cannot import name '_finalize_rasterization' from 'matplotlib.artist' (c:\ProgramData\Anaconda3\lib\site-packages\matplotlib\artist.py)
from turtle import color


data = [['E001', 'M', 34, 123, 'Normal', 50],
        ['E002', 'F', 40, 114, 'Overweight', 150],
        ['E003', 'F', 37, 135, 'Obesity', 169],
        ['E004', 'M', 30, 139, 'Underweight', 210],
        ['E005', 'F', 44, 117, 'Underweight', 183],
        ['E006', 'M', 36, 121, 'Normal', 80],
        ['E007', 'M', 32, 133, 'Obesity', 166],
        ['E008', 'F', 26, 140, 'Normal', 120],
        ['E009', 'M', 32, 133, 'Normal', 75],
        ['E010', 'M', 36, 133, 'Underweight', 51] ]
df = pd.DataFrame(data, columns = ['EMPID', 'Gender','Age', 'Sales','BMI', 'Income'] )

df.plot.box()
plt.show()
plt.boxplot(df['Age'])
plt.title(' plot for sales persons',color='red')

plt.show()


import numpy
import matplotlib.pyplot as plt

x = numpy.random.normal(0.0, 1.0, 10000)

plt.hist(x, 100)
plt.show()

# Import libraries
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import numpy as np
 
 
# Create axis
axes = [5, 5, 5]
 
# Create Data
data = np.ones(axes, dtype=np.bool)
 
# Control Transparency
alpha = 0.9
 
# Control colour
colors = np.empty(axes + [4], dtype=np.float32)
 
colors[:] = [1, 1, 0, alpha]  # red
 
# Plot figure
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
 
# Voxels is used to customizations of the
# sizes, positions and colors.
ax.voxels(data, facecolors=colors)
{(0, 0, 0): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc840e80>,
 (0, 0, 4): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc890250>,
 (0, 1, 0): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc890c70>,
 (0, 1, 4): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc890880>,
 (0, 2, 0): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc8906d0>,
 (0, 2, 4): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc890a30>,
 (0, 3, 0): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc8714c0>,
 (0, 3, 4): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc871ca0>,
 (0, 4, 0): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc871820>,
 (0, 4, 4): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc8713a0>,
 (1, 0, 0): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc8719a0>,
 (1, 0, 4): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc82d0a0>,
 (1, 1, 0): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc82d4f0>,
 (1, 1, 4): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc82d610>,
 (1, 2, 0): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc82df10>,
 (1, 2, 4): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc82d6a0>,
 (1, 3, 0): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc82d130>,
 (1, 3, 4): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc86bfd0>,
 (1, 4, 0): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc86b8e0>,
 (1, 4, 4): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc86b4c0>,
 (2, 0, 0): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc86b3d0>,
 (2, 0, 4): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc877ca0>,
 (2, 1, 0): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc877d60>,
 (2, 1, 4): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc877c10>,
 (2, 2, 0): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc877760>,
 (2, 2, 4): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc877490>,
 (2, 3, 0): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc8774c0>,
 (2, 3, 4): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc88cdc0>,
 (2, 4, 0): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc88c520>,
 (2, 4, 4): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc88c3d0>,
 (3, 0, 0): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc88cb50>,
 (3, 0, 4): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc7d5f40>,
 (3, 1, 0): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc7d5550>,
 (3, 1, 4): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc7d5e80>,
 (3, 2, 0): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc7d56d0>,
 (3, 2, 4): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0x9607400>,
 (3, 3, 0): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc6e1250>,
 (3, 3, 4): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc67e820>,
 (3, 4, 0): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc67ee80>,
 (3, 4, 4): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc67efa0>,
 (4, 0, 0): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc67e4f0>,
 (4, 0, 4): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc67e190>,
 (4, 1, 0): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc6c4490>,
 (4, 1, 4): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc6c4a30>,
 (4, 2, 0): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc6c4340>,
 (4, 2, 4): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc6c4e20>,
 (4, 3, 0): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc6a9370>,
 (4, 3, 4): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc6a95b0>,
 (4, 4, 0): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc6a9100>,
 (4, 4, 4): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc6a9b50>,
 (0, 0, 1): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc6a9940>,
 (4, 0, 1): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc6b6910>,
 (0, 0, 2): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc6b6760>,
 (4, 0, 2): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc6b6d00>,
 (0, 0, 3): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc6b6370>,
 (4, 0, 3): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc6b6970>,
 (0, 1, 1): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc6bc0d0>,
 (4, 1, 1): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc6bcc40>,
 (0, 1, 2): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc6bc340>,
 (4, 1, 2): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc6bc310>,
 (0, 1, 3): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc6bcf70>,
 (4, 1, 3): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc69bd90>,
 (0, 2, 1): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc69b2e0>,
 (4, 2, 1): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc69b730>,
 (0, 2, 2): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc69bb50>,
 (4, 2, 2): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc69b7f0>,
 (0, 2, 3): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc6d0f40>,
 (4, 2, 3): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc6d0850>,
 (0, 3, 1): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc6c8d60>,
 (4, 3, 1): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc6c8910>,
 (0, 3, 2): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc6c82b0>,
 (4, 3, 2): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc6c8eb0>,
 (0, 3, 3): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc6dc730>,
 (4, 3, 3): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc6dcb50>,
 (0, 4, 1): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0x9db4e50>,
 (4, 4, 1): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc5c6070>,
 (0, 4, 2): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc5c63d0>,
 (4, 4, 2): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc5c6b50>,
 (0, 4, 3): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc5c6c10>,
 (4, 4, 3): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc5c6fa0>,
 (1, 0, 1): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc5d64c0>,
 (1, 4, 1): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc5d66a0>,
 (2, 0, 1): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc5d6cd0>,
 (2, 4, 1): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc5d6d60>,
 (3, 0, 1): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0x9cf4a90>,
 (3, 4, 1): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc64d430>,
 (1, 0, 2): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc635130>,
 (1, 4, 2): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc635310>,
 (2, 0, 2): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc635c40>,
 (2, 4, 2): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc635fa0>,
 (3, 0, 2): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc6356a0>,
 (3, 4, 2): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc635e50>,
 (1, 0, 3): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc5a5640>,
 (1, 4, 3): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc5a5ee0>,
 (2, 0, 3): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc5a58b0>,
 (2, 4, 3): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc5a5c40>,
 (3, 0, 3): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc5a5160>,
 (3, 4, 3): <mpl_toolkits.mplot3d.art3d.Poly3DCollection at 0xc6220a0>}

import numpy as np
import matplotlib.pyplot as nplot
nplot.style.use("seaborn-whitegrid")
time =np.arange(0,12.5,0.1)
amp= np.sin(time)
nplot.plot(time,amp)

amp= np.cos(time)
nplot.plot(time,amp)
nplot.show()

plt.pie(df['Age'], labels = {"Emp1", "Emp1", "C","D", "E", "F", "G", "H", "I", "J"},
autopct ='% 1.1f %%', shadow = True)
plt.show()
plt.pie(df['Income'], labels = {"A", "B", "C", "D", "E", "F","G", "H", "I", "J"},
autopct ='% 1.1f %%', shadow = True)
plt.show()
plt.pie(df['Sales'], labels = {"A", "B", "C", "D", "E", "F", "G", "H", "I", "J"},
autopct ='% 1.1f %%', shadow = True)
plt.show()



data = [['E001', 'M', 34, 123, 'Normal', 50],
        ['E001', 'M', 35, 123, 'Normal', 52],
        ['E0012', 'M', 36, 123, 'Normal', 49],
        ['E0013', 'M', 37, 123, 'Normal', 54],
        ['E002', 'F', 40, 114, 'Overweight', 150],
        ['E003', 'F', 37, 135, 'Obesity', 169],
        ['E004', 'M', 30, 139, 'Underweight', 210],
        ['E005', 'F', 44, 117, 'Underweight', 183],
        ['E006', 'M', 36, 121, 'Normal', 80],
        ['E007', 'M', 32, 133, 'Obesity', 166],
        ['E008', 'F', 26, 140, 'Normal', 120],
        ['E009', 'M', 32, 133, 'Normal', 75],
        ['E010', 'M', 36, 133, 'Underweight', 40] ]
df = pd.DataFrame(data, columns = ['EMPID', 'Gender','Age', 'Sales','BMI', 'Income'] )

plt.scatter(df['Income'],df['Age'])
plt.show()

import numpy as np
import scipy as sp
import matplotlib.pyplot as plt

# %matplotlib inline 
k = np.arange(0,8) 
x = np.cos(2*k*np.pi/4) 
plt.stem(k,x,use_line_collection=True) 
<StemContainer object of 3 artists>

vec = np.array([[-2],[-2]])
origin=np.zeros(vec.shape)
plt.figure(figsize=(6,6))
plt.quiver(*origin, *vec, color=['g'],scale=0.8,units='xy')
plt.grid()
plt.xlim(-5,5)
plt.ylim(-5,5)
plt.gca().set_aspect('equal')
plt.show()

vec = np.array([[-3],[2]])
origin=np.zeros(vec.shape)
plt.figure(figsize=(6,6))
plt.quiver(*origin, *vec, color=['b'],scale=1,units='xy')

plt.xlim(-5,5)
plt.ylim(-5,5)
plt.grid()
plt.gca().set_aspect('equal')
# plt.show()

theta = np.radians(-90)
R = np.zeros((2,2))
R[0,0]=np.cos(theta)
R[0,1]=-np.sin(theta)
R[1,0]=np.sin(theta)
R[1,1]=np.cos(theta)
print(R)

new = np.zeros(vec.shape)
new[0] = R[1,1]*vec[0] + R[0,1]*vec[1]
new[0] = R[1,0]*vec[0] + R[0,0]*vec[1]
new =R.dot(vec)

origin = np.zeros(new.shape)

plt.figure(figsize=(6,6))
plt.quiver(*origin,*new, color=['r'],scale=1,units='xy')
plt.grid()
plt.xlim(-5,5)
plt.ylim(-5,5)
plt.grid()
plt.gca().set_aspect('equal')
plt.show()
[[ 6.123234e-17  1.000000e+00]
 [-1.000000e+00  6.123234e-17]]


import numpy as np
from scipy.stats.contingency import margins

join_probability_X_Y = np.array([
                [0.01, 0.02, 0.04, 0.04],
                [0.03, 0.24, 0.15, 0.06],
                [0.04, 0.10, 0.08, 0.08],
                [0.02, 0.04, 0.03, 0.02]
            ])


x, y = margins(join_probability_X_Y)

print(x.T)
print(y.T)
[[0.11 0.48 0.3  0.11]]
[[0.1]
 [0.4]
 [0.3]
 [0.2]]
# imports specific to the plots in this example
import numpy as np
from matplotlib import cm
from matplotlib.pyplot import plt
from mpl_toolkits.mplot3d.axes3d import get_test_data
# Twice as wide as it is tall.
fig = plt.figure(figsize=plt.figaspect(0.5))
#---- First subplot
# Note that the declaration "projection='3d'"
# is required for 3d plots!
ax = fig.add_subplot(1, 2, 1, projection='3d')
# Generate the grid
X = np.arange(-5, 5, 0.1)
Y = np.arange(-5, 5, 0.1)
X, Y = np.meshgrid(X, Y)
# Generate the surface data
R = np.sqrt(X**2+Y**2)
Z = np.sin(R)
# Plot the surface
surf = ax.plot_surface(X, Y, Z, rstride=1, cstride=1,
cmap=cm.GnBu, linewidth=0, antialiased=False)
ax.set_zlim3d(-1.01, 1.01)
fig.colorbar(surf, shrink=0.5, aspect=10)
#---- Second subplot
ax = fig.add_subplot(1, 2, 2, projection='3d')
X, Y, Z = get_test_data(0.05)
ax.plot_wireframe(X, Y, Z, rstride=10, cstride=10)
outfile = '3dGraph.png'
plt.savefig(outfile, dpi=200)
print('Image saved to {0}'.format(outfile))
plt.show()
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
g:\Backup Sep 2 2022\Desk\sample\Module3\practical.ipynb Cell 18 in <cell line: 4>()
      <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X23sZmlsZQ%3D%3D?line=1'>2</a> import numpy as np
      <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X23sZmlsZQ%3D%3D?line=2'>3</a> from matplotlib import cm
----> <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X23sZmlsZQ%3D%3D?line=3'>4</a> from matplotlib.pyplot import plt
      <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X23sZmlsZQ%3D%3D?line=4'>5</a> from mpl_toolkits.mplot3d.axes3d import get_test_data
      <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X23sZmlsZQ%3D%3D?line=5'>6</a> # Twice as wide as it is tall.

File c:\ProgramData\Anaconda3\lib\site-packages\matplotlib\pyplot.py:57, in <module>
     55 from matplotlib import docstring
     56 from matplotlib.backend_bases import FigureCanvasBase, MouseButton
---> 57 from matplotlib.figure import Figure, figaspect
     58 from matplotlib.gridspec import GridSpec, SubplotSpec
     59 from matplotlib import rcParams, rcParamsDefault, get_backend, rcParamsOrig

File c:\ProgramData\Anaconda3\lib\site-packages\matplotlib\figure.py:26, in <module>
     24 import matplotlib as mpl
     25 from matplotlib import _blocking_input, docstring, projections
---> 26 from matplotlib.artist import (
     27     Artist, allow_rasterization, _finalize_rasterization)
     28 from matplotlib.backend_bases import (
     29     FigureCanvasBase, NonGuiException, MouseButton, _get_renderer)
     30 import matplotlib._api as _api

ImportError: cannot import name '_finalize_rasterization' from 'matplotlib.artist' (c:\ProgramData\Anaconda3\lib\site-packages\matplotlib\artist.py)
from tkinter import PROJECTING
import numpy as np
import matplotlib.pyplot as plt

fig= plt.figure()

ax = plt.axes(PROJECTING='3d')
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
g:\Backup Sep 2 2022\Desk\sample\Module3\practical.ipynb Cell 19 in <cell line: 3>()
      <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X24sZmlsZQ%3D%3D?line=0'>1</a> from tkinter import PROJECTING
      <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X24sZmlsZQ%3D%3D?line=1'>2</a> import numpy as np
----> <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X24sZmlsZQ%3D%3D?line=2'>3</a> import matplotlib.pyplot as plt
      <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X24sZmlsZQ%3D%3D?line=4'>5</a> fig= plt.figure()
      <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X24sZmlsZQ%3D%3D?line=6'>7</a> ax = plt.axes(PROJECTING='3d')

File c:\ProgramData\Anaconda3\lib\site-packages\matplotlib\pyplot.py:57, in <module>
     55 from matplotlib import docstring
     56 from matplotlib.backend_bases import FigureCanvasBase, MouseButton
---> 57 from matplotlib.figure import Figure, figaspect
     58 from matplotlib.gridspec import GridSpec, SubplotSpec
     59 from matplotlib import rcParams, rcParamsDefault, get_backend, rcParamsOrig

File c:\ProgramData\Anaconda3\lib\site-packages\matplotlib\figure.py:26, in <module>
     24 import matplotlib as mpl
     25 from matplotlib import _blocking_input, docstring, projections
---> 26 from matplotlib.artist import (
     27     Artist, allow_rasterization, _finalize_rasterization)
     28 from matplotlib.backend_bases import (
     29     FigureCanvasBase, NonGuiException, MouseButton, _get_renderer)
     30 import matplotlib._api as _api

ImportError: cannot import name '_finalize_rasterization' from 'matplotlib.artist' (c:\ProgramData\Anaconda3\lib\site-packages\matplotlib\artist.py)
# importing mplot3d toolkits, numpy and matplotlib
from mpl_toolkits import mplot3d
import numpy as np
import matplotlib.pyplot as plt
 
fig = plt.figure()
 
# syntax for 3-D projection
ax = plt.axes(projection ='3d')
 
# defining all 3 axes
z = np.linspace(0, 1, 100)
x = z * np.sin(25 * z)
y = z * np.cos(25 * z)
 
# plotting
ax.plot3D(x, y, z, 'green')
ax.set_title('3D line plot geeks for geeks')
plt.show()
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
g:\Backup Sep 2 2022\Desk\sample\Module3\practical.ipynb Cell 20 in <cell line: 4>()
      <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X25sZmlsZQ%3D%3D?line=1'>2</a> from mpl_toolkits import mplot3d
      <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X25sZmlsZQ%3D%3D?line=2'>3</a> import numpy as np
----> <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X25sZmlsZQ%3D%3D?line=3'>4</a> import matplotlib.pyplot as plt
      <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X25sZmlsZQ%3D%3D?line=5'>6</a> fig = plt.figure()
      <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X25sZmlsZQ%3D%3D?line=7'>8</a> # syntax for 3-D projection

ModuleNotFoundError: No module named 'matplotlib.pyplot'
import matplotlib.pyplot as plt

squares = [1, 4, 9, 16, 25]
plt.plot(squares)
plt.show()
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
g:\Backup Sep 2 2022\Desk\sample\Module3\practical.ipynb Cell 21 in <cell line: 1>()
----> <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X26sZmlsZQ%3D%3D?line=0'>1</a> import matplotlib.pyplot as plt
      <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X26sZmlsZQ%3D%3D?line=2'>3</a> squares = [1, 4, 9, 16, 25]
      <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X26sZmlsZQ%3D%3D?line=3'>4</a> plt.plot(squares)

ModuleNotFoundError: No module named 'matplotlib.pyplot'
from scipy import stats

bernoulliDist = stats.bernoulli(0.5)
p_tails =bernoulliDist.pmf(0)
p_heads =bernoulliDist.pmf(1)

trials = bernoulliDist.rvs(10)
trials
array([1, 1, 0, 1, 1, 1, 0, 0, 1, 0])
from scipy import stats
import numpy as np
(p,num )=(0.5,4)

binomDist = stats.binom(num,p)
binomDist.pmf(np.arange(5))
array([0.0625, 0.25  , 0.375 , 0.25  , 0.0625])
from scipy import stats
import numpy as np

mu = -2
sigma = 1.0

myDistribution = stats.norm(mu,sigma)
significanceLevel = 0.05

myDistribution.ppf([significanceLevel/2, 1-significanceLevel/2])
array([-1.95996398,  1.95996398])
import numpy as np
import matplotlib.pyplot as plt

x = np.arange(100)
y = 150 + 3*x + 0.03*x**2+5*np.random.randn(len(x))

# Create the Design Matrices for the linear, quadratic,
# and cubic fit
M1 = np.vstack( (np.ones_like(x), x) ).T
M2 = np.vstack( (np.ones_like(x), x, x**2) ).T
M3 = np.vstack( (np.ones_like(x), x, x**2, x**3) ).T

# an equivalent alternative solution with statsmodels would be
# M1 = sm.add_constant(x)

# Solve the equations
p1 = np.linalg.lstsq(M1, y)
p2 = np.linalg.lstsq(M2, y)
p3 = np.linalg.lstsq(M3, y)
 
np.set_printoptions(precision=3)
print('The coefficients from the linear fit: {0}'.format(p1[0]))

print('The coefficients from the quadratic fit: {0}'  .format(p2[0]))
print('The coefficients from the cubic fit: {0}'  .format(p3[0]))
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
g:\Backup Sep 2 2022\Desk\sample\Module3\practical.ipynb Cell 25 in <cell line: 2>()
      <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X33sZmlsZQ%3D%3D?line=0'>1</a> import numpy as np
----> <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X33sZmlsZQ%3D%3D?line=1'>2</a> import matplotlib.pyplot as plt
      <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X33sZmlsZQ%3D%3D?line=3'>4</a> x = np.arange(100)
      <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X33sZmlsZQ%3D%3D?line=4'>5</a> y = 150 + 3*x + 0.03*x**2+5*np.random.randn(len(x))

File c:\ProgramData\Anaconda3\lib\site-packages\matplotlib\pyplot.py:57, in <module>
     55 from matplotlib import docstring
     56 from matplotlib.backend_bases import FigureCanvasBase, MouseButton
---> 57 from matplotlib.figure import Figure, figaspect
     58 from matplotlib.gridspec import GridSpec, SubplotSpec
     59 from matplotlib import rcParams, rcParamsDefault, get_backend, rcParamsOrig

File c:\ProgramData\Anaconda3\lib\site-packages\matplotlib\figure.py:26, in <module>
     24 import matplotlib as mpl
     25 from matplotlib import _blocking_input, docstring, projections
---> 26 from matplotlib.artist import (
     27     Artist, allow_rasterization, _finalize_rasterization)
     28 from matplotlib.backend_bases import (
     29     FigureCanvasBase, NonGuiException, MouseButton, _get_renderer)
     30 import matplotlib._api as _api

ImportError: cannot import name '_finalize_rasterization' from 'matplotlib.artist' (c:\ProgramData\Anaconda3\lib\site-packages\matplotlib\artist.py)
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import TfidfVectorizer
from time import time

categories = [
    "alt.atheism",
    "talk.religion.misc",
    "comp.graphics",
    "sci.space",
]


def size_mb(docs):
    return sum(len(s.encode("utf-8")) for s in docs) / 1e6


def load_dataset(verbose=False, remove=()):
    """Load and vectorize the 20 newsgroups dataset."""

    data_train = fetch_20newsgroups(
        subset="train",
        categories=categories,
        shuffle=True,
        random_state=42,
        remove=remove,
    )

    data_test = fetch_20newsgroups(
        subset="test",
        categories=categories,
        shuffle=True,
        random_state=42,
        remove=remove,
    )

    # order of labels in `target_names` can be different from `categories`
    target_names = data_train.target_names

    # split target in a training set and a test set
    y_train, y_test = data_train.target, data_test.target

    # Extracting features from the training data using a sparse vectorizer
    t0 = time()
    vectorizer = TfidfVectorizer(
        sublinear_tf=True, max_df=0.5, min_df=5, stop_words="english"
    )
    X_train = vectorizer.fit_transform(data_train.data)
    duration_train = time() - t0

    # Extracting features from the test data using the same vectorizer
    t0 = time()
    X_test = vectorizer.transform(data_test.data)
    duration_test = time() - t0

    feature_names = vectorizer.get_feature_names_out()

    if verbose:

        # compute size of loaded data
        data_train_size_mb = size_mb(data_train.data)
        data_test_size_mb = size_mb(data_test.data)

        print(
            f"{len(data_train.data)} documents - "
            f"{data_train_size_mb:.2f}MB (training set)"
        )
        print(f"{len(data_test.data)} documents - {data_test_size_mb:.2f}MB (test set)")
        print(f"{len(target_names)} categories")
        print(
            f"vectorize training done in {duration_train:.3f}s "
            f"at {data_train_size_mb / duration_train:.3f}MB/s"
        )
        print(f"n_samples: {X_train.shape[0]}, n_features: {X_train.shape[1]}")
        print(
            f"vectorize testing done in {duration_test:.3f}s "
            f"at {data_test_size_mb / duration_test:.3f}MB/s"
        )
        print(f"n_samples: {X_test.shape[0]}, n_features: {X_test.shape[1]}")

    return X_train, X_test, y_train, y_test, feature_names, target_names


# %%
# Analysis of a bag-of-words document classifier
# ==============================================
#
# We will now train a classifier twice, once on the text samples including
# metadata and once after stripping the metadata. For both cases we will analyze
# the classification errors on a test set using a confusion matrix and inspect
# the coefficients that define the classification function of the trained
# models.
#
# Model without metadata stripping
# --------------------------------
#
# We start by using the custom function `load_dataset` to load the data without
# metadata stripping.

X_train, X_test, y_train, y_test, feature_names, target_names = load_dataset(
    verbose=True
)

# %%
# Our first model is an instance of the
# :class:`~sklearn.linear_model.RidgeClassifier` class. This is a linear
# classification model that uses the mean squared error on {-1, 1} encoded
# targets, one for each possible class. Contrary to
# :class:`~sklearn.linear_model.LogisticRegression`,
# :class:`~sklearn.linear_model.RidgeClassifier` does not
# provide probabilistic predictions (no `predict_proba` method),
# but it is often faster to train.

from sklearn.linear_model import RidgeClassifier

clf = RidgeClassifier(tol=1e-2, solver="sparse_cg")
clf.fit(X_train, y_train)
pred = clf.predict(X_test)

# %%
# We plot the confusion matrix of this classifier to find if there is a pattern
# in the classification errors.

import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay

fig, ax = plt.subplots(figsize=(10, 5))
ConfusionMatrixDisplay.from_predictions(y_test, pred, ax=ax)
ax.xaxis.set_ticklabels(target_names)
ax.yaxis.set_ticklabels(target_names)
_ = ax.set_title(
    f"Confusion Matrix for {clf.__class__.__name__}\non the original documents"
)

# %%
# The confusion matrix highlights that documents of the `alt.atheism` class are
# often confused with documents with the class `talk.religion.misc` class and
# vice-versa which is expected since the topics are semantically related.
#
# We also observe that some documents of the `sci.space` class can be misclassified as
# `comp.graphics` while the converse is much rarer. A manual inspection of those
# badly classified documents would be required to get some insights on this
# asymmetry. It could be the case that the vocabulary of the space topic could
# be more specific than the vocabulary for computer graphics.
#
# We can gain a deeper understanding of how this classifier makes its decisions
# by looking at the words with the highest average feature effects:

import pandas as pd
import numpy as np


def plot_feature_effects():
    # learned coefficients weighted by frequency of appearance
    average_feature_effects = clf.coef_ * np.asarray(X_train.mean(axis=0)).ravel()

    for i, label in enumerate(target_names):
        top5 = np.argsort(average_feature_effects[i])[-5:][::-1]
        if i == 0:
            top = pd.DataFrame(feature_names[top5], columns=[label])
            top_indices = top5
        else:
            top[label] = feature_names[top5]
            top_indices = np.concatenate((top_indices, top5), axis=None)
    top_indices = np.unique(top_indices)
    predictive_words = feature_names[top_indices]

    # plot feature effects
    bar_size = 0.25
    padding = 0.75
    y_locs = np.arange(len(top_indices)) * (4 * bar_size + padding)

    fig, ax = plt.subplots(figsize=(10, 8))
    for i, label in enumerate(target_names):
        ax.barh(
            y_locs + (i - 2) * bar_size,
            average_feature_effects[i, top_indices],
            height=bar_size,
            label=label,
        )
    ax.set(
        yticks=y_locs,
        yticklabels=predictive_words,
        ylim=[
            0 - 4 * bar_size,
            len(top_indices) * (4 * bar_size + padding) - 4 * bar_size,
        ],
    )
    ax.legend(loc="lower right")

    print("top 5 keywords per class:")
    print(top)

    return ax


_ = plot_feature_effects().set_title("Average feature effect on the original data")

# %%
# We can observe that the most predictive words are often strongly positively
# associated with a single class and negatively associated with all the other
# classes. Most of those positive associations are quite easy to interpret.
# However, some words such as `"god"` and `"people"` are positively associated to
# both `"talk.misc.religion"` and `"alt.atheism"` as those two classes expectedly
# share some common vocabulary. Notice however that there are also words such as
# `"christian"` and `"morality"` that are only positively associated with
# `"talk.misc.religion"`. Furthermore, in this version of the dataset, the word
# `"caltech"` is one of the top predictive features for atheism due to pollution
# in the dataset coming from some sort of metadata such as the email addresses
# of the sender of previous emails in the discussion as can be seen below:

data_train = fetch_20newsgroups(
    subset="train", categories=categories, shuffle=True, random_state=42
)

for doc in data_train.data:
    if "caltech" in doc:
        print(doc)
        break

# %%
# Such headers, signature footers (and quoted metadata from previous messages)
# can be considered side information that artificially reveals the newsgroup by
# identifying the registered members and one would rather want our text
# classifier to only learn from the "main content" of each text document instead
# of relying on the leaked identity of the writers.
#
# Model with metadata stripping
# -----------------------------
#
# The `remove` option of the 20 newsgroups dataset loader in scikit-learn allows
# to heuristically attempt to filter out some of this unwanted metadata that
# makes the classification problem artificially easier. Be aware that such
# filtering of the text contents is far from perfect.
#
# Let us try to leverage this option to train a text classifier that does not
# rely too much on this kind of metadata to make its decisions:
(
    X_train,
    X_test,
    y_train,
    y_test,
    feature_names,
    target_names,
) = load_dataset(remove=("headers", "footers", "quotes"))

clf = RidgeClassifier(tol=1e-2, solver="sparse_cg")
clf.fit(X_train, y_train)
pred = clf.predict(X_test)

fig, ax = plt.subplots(figsize=(10, 5))
ConfusionMatrixDisplay.from_predictions(y_test, pred, ax=ax)
ax.xaxis.set_ticklabels(target_names)
ax.yaxis.set_ticklabels(target_names)
_ = ax.set_title(
    f"Confusion Matrix for {clf.__class__.__name__}\non filtered documents"
)

# %%
# By looking at the confusion matrix, it is more evident that the scores of the
# model trained with metadata were over-optimistic. The classification problem
# without access to the metadata is less accurate but more representative of the
# intended text classification problem.

_ = plot_feature_effects().set_title("Average feature effects on filtered documents")

# %%
# In the next section we keep the dataset without metadata to compare several
# classifiers.

# %%
# Benchmarking classifiers
# ========================
#
# Scikit-learn provides many different kinds of classification algorithms. In
# this section we will train a selection of those classifiers on the same text
# classification problem and measure both their generalization performance
# (accuracy on the test set) and their computation performance (speed), both at
# training time and testing time. For such purpose we define the following
# benchmarking utilities:

from sklearn.utils.extmath import density
from sklearn import metrics


def benchmark(clf, custom_name=False):
    print("_" * 80)
    print("Training: ")
    print(clf)
    t0 = time()
    clf.fit(X_train, y_train)
    train_time = time() - t0
    print(f"train time: {train_time:.3}s")

    t0 = time()
    pred = clf.predict(X_test)
    test_time = time() - t0
    print(f"test time:  {test_time:.3}s")

    score = metrics.accuracy_score(y_test, pred)
    print(f"accuracy:   {score:.3}")

    if hasattr(clf, "coef_"):
        print(f"dimensionality: {clf.coef_.shape[1]}")
        print(f"density: {density(clf.coef_)}")
        print()

    print()
    if custom_name:
        clf_descr = str(custom_name)
    else:
        clf_descr = clf.__class__.__name__
    return clf_descr, score, train_time, test_time


# %%
# We now train and test the datasets with 8 different classification models and
# get performance results for each model. The goal of this study is to highlight
# the computation/accuracy tradeoffs of different types of classifiers for
# such a multi-class text classification problem.
#
# Notice that the most important hyperparameters values were tuned using a grid
# search procedure not shown in this notebook for the sake of simplicity.

from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.linear_model import SGDClassifier
from sklearn.naive_bayes import ComplementNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import NearestCentroid
from sklearn.ensemble import RandomForestClassifier


results = []
for clf, name in (
    (LogisticRegression(C=5, max_iter=1000), "Logistic Regression"),
    (RidgeClassifier(alpha=1.0, solver="sparse_cg"), "Ridge Classifier"),
    (KNeighborsClassifier(n_neighbors=100), "kNN"),
    (RandomForestClassifier(), "Random Forest"),
    # L2 penalty Linear SVC
    (LinearSVC(C=0.1, dual=False, max_iter=1000), "Linear SVC"),
    # L2 penalty Linear SGD
    (
        SGDClassifier(
            loss="log_loss", alpha=1e-4, n_iter_no_change=3, early_stopping=True
        ),
        "log-loss SGD",
    ),
    # NearestCentroid (aka Rocchio classifier)
    (NearestCentroid(), "NearestCentroid"),
    # Sparse naive Bayes classifier
    (ComplementNB(alpha=0.1), "Complement naive Bayes"),
):
    print("=" * 80)
    print(name)
    results.append(benchmark(clf, name))

# %%
# Plot accuracy, training and test time of each classifier
# ========================================================
#
# The scatter plots show the trade-off between the test accuracy and the
# training and testing time of each classifier.

indices = np.arange(len(results))

results = [[x[i] for x in results] for i in range(4)]

clf_names, score, training_time, test_time = results
training_time = np.array(training_time)
test_time = np.array(test_time)

fig, ax1 = plt.subplots(figsize=(10, 8))
ax1.scatter(score, training_time, s=60)
ax1.set(
    title="Score-training time trade-off",
    yscale="log",
    xlabel="test accuracy",
    ylabel="training time (s)",
)
fig, ax2 = plt.subplots(figsize=(10, 8))
ax2.scatter(score, test_time, s=60)
ax2.set(
    title="Score-test time trade-off",
    yscale="log",
    xlabel="test accuracy",
    ylabel="test time (s)",
)

for i, txt in enumerate(clf_names):
    ax1.annotate(txt, (score[i], training_time[i]))
    ax2.annotate(txt, (score[i], test_time[i]))

# %%
# The naive Bayes model has the best trade-off between score and
# training/testing time, while Random Forest is both slow to train, expensive to
# predict and has a comparatively bad accuracy. This is expected: for
# high-dimensional prediction problems, linear models are often better suited as
# most problems become linearly separable when the feature space has 10,000
# dimensions or more.
#
# The difference in training speed and accuracy of the linear models can be
# explained by the choice of the loss function they optimize and the kind of
# regularization they use. Be aware that some linear models with the same loss
# but a different solver or regularization configuration may yield different
# fitting times and test accuracy. We can observe on the second plot that once
# trained, all linear models have approximately the same prediction speed which
# is expected because they all implement the same prediction function.
#
# KNeighborsClassifier has a relatively low accuracy and has the highest testing
# time. The long prediction time is also expected: for each prediction the model
# has to compute the pairwise distances between the testing sample and each
# document in the training set, which is computationally expensive. Furthermore,
# the "curse of dimensionality" harms the ability of this model to yield
# competitive accuracy in the high dimensional feature space of text
# classification problems.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
g:\Backup Sep 2 2022\Desk\sample\Module3\practical.ipynb Cell 26 in <cell line: 99>()
     <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X34sZmlsZQ%3D%3D?line=79'>80</a>     return X_train, X_test, y_train, y_test, feature_names, target_names
     <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X34sZmlsZQ%3D%3D?line=82'>83</a> # %%
     <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X34sZmlsZQ%3D%3D?line=83'>84</a> # Analysis of a bag-of-words document classifier
     <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X34sZmlsZQ%3D%3D?line=84'>85</a> # ==============================================
   (...)
     <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X34sZmlsZQ%3D%3D?line=95'>96</a> # We start by using the custom function `load_dataset` to load the data without
     <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X34sZmlsZQ%3D%3D?line=96'>97</a> # metadata stripping.
---> <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X34sZmlsZQ%3D%3D?line=98'>99</a> X_train, X_test, y_train, y_test, feature_names, target_names = load_dataset(
    <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X34sZmlsZQ%3D%3D?line=99'>100</a>     verbose=True
    <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X34sZmlsZQ%3D%3D?line=100'>101</a> )
    <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X34sZmlsZQ%3D%3D?line=102'>103</a> # %%
    <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X34sZmlsZQ%3D%3D?line=103'>104</a> # Our first model is an instance of the
    <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X34sZmlsZQ%3D%3D?line=104'>105</a> # :class:`~sklearn.linear_model.RidgeClassifier` class. This is a linear
   (...)
    <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X34sZmlsZQ%3D%3D?line=109'>110</a> # provide probabilistic predictions (no `predict_proba` method),
    <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X34sZmlsZQ%3D%3D?line=110'>111</a> # but it is often faster to train.
    <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X34sZmlsZQ%3D%3D?line=112'>113</a> from sklearn.linear_model import RidgeClassifier

g:\Backup Sep 2 2022\Desk\sample\Module3\practical.ipynb Cell 26 in load_dataset(verbose, remove)
     <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X34sZmlsZQ%3D%3D?line=51'>52</a> X_test = vectorizer.transform(data_test.data)
     <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X34sZmlsZQ%3D%3D?line=52'>53</a> duration_test = time() - t0
---> <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X34sZmlsZQ%3D%3D?line=54'>55</a> feature_names = vectorizer.get_feature_names_out()
     <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X34sZmlsZQ%3D%3D?line=56'>57</a> if verbose:
     <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X34sZmlsZQ%3D%3D?line=57'>58</a> 
     <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X34sZmlsZQ%3D%3D?line=58'>59</a>     # compute size of loaded data
     <a href='vscode-notebook-cell:/g%3A/Backup%20Sep%202%202022/Desk/sample/Module3/practical.ipynb#X34sZmlsZQ%3D%3D?line=59'>60</a>     data_train_size_mb = size_mb(data_train.data)

AttributeError: 'TfidfVectorizer' object has no attribute 'get_feature_names_out'
# Python program to demonstrate
# basic array characteristics
import numpy as np
 
# Creating array object
arr = np.array( [[ 1.5, 2.3, 3.6],[ 4, 2, 5]] )
 
# Printing type of arr object
print("Array is of type: ", type(arr))
 
# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)
 
# Printing shape of array
print("Shape of array: ", arr.shape)
 
# Printing size (total number of elements) of array
print("Size of array: ", arr.size)
 
# Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)
Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  float64
# Python program to demonstrate
# array creation techniques
import numpy as np
 
# Creating array from list with type float
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float')
print ("Array created using passed list:\n", a)
 
# Creating array from tuple
b = np.array((1 , 3, 2))
print ("\nArray created using passed tuple:\n", b)
 
# Creating a 3X4 array with all zeros
c = np.zeros((3, 4))
print ("\nAn array initialized with all zeros:\n", c)
 
# Create a constant value array of complex type
d = np.full((3, 3), 6, dtype = 'complex')
print ("\nAn array initialized with all 6s."
            "Array type is complex:\n", d)
 
# Create an array with random values
e = np.random.random((2, 2))
print ("\nA random array:\n", e)
 
# Create a sequence of integers
# from 0 to 30 with steps of 5
f = np.arange(0, 30, 5)
print ("\nA sequential array with steps of 5:\n", f)
 
# Create a sequence of 10 values in range 0 to 5
g = np.linspace(0, 5, 10)
print ("\nA sequential array with 10 values between"
                                        "0 and 5:\n", g)
 
# Reshaping 3X4 array to 2X2X3 array
arr = np.array([[1, 2, 3, 4],
                [5, 2, 4, 2],
                [1, 2, 0, 1]])
 
newarr = arr.reshape(2, 2, 3)
 
print ("\nOriginal array:\n", arr)
print ("Reshaped array:\n", newarr)
 
# Flatten array
arr = np.array([[1, 2, 3], [4, 5, 6]])
flarr = arr.flatten()
 
print ("\nOriginal array:\n", arr)
print ("Fattened array:\n", flarr)
Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]

Array created using passed tuple:
 [1 3 2]

An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

An array initialized with all 6s.Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]

A random array:
 [[0.89937539 0.64296692]
 [0.67560679 0.5219163 ]]

A sequential array with steps of 5:
 [ 0  5 10 15 20 25]

A sequential array with 10 values between0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array:
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]

Original array:
 [[1 2 3]
 [4 5 6]]
Fattened array:
 [1 2 3 4 5 6]
l1=[1,2]
l2=[3,4]    
l3=l1+l2
print(l3)
[1, 2, 3, 4]
# Python program to demonstrate
# unary operators in numpy
import numpy as np
 
arr = np.array([[1, 5, 6],
                [4, 7, 2],
                [3, 1, 9]])
print(arr)
# maximum element of array
print ("Largest element is:", arr.max())
print ("Row-wise maximum elements:",
                    arr.max(axis = 1))
 
# minimum element of array
print ("Column-wise minimum elements:",
                        arr.min(axis = 0))
 
# sum of array elements
print ("Sum of all array elements:",
                            arr.sum())
 
# cumulative sum along each row
print ("Cumulative sum along each row:\n",
                        arr.cumsum(axis = 1))
[[1 5 6]
 [4 7 2]
 [3 1 9]]
Largest element is: 9
Row-wise maximum elements: [6 7 9]
Column-wise minimum elements: [1 1 2]
Sum of all array elements: 38
Cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]
# Python program to demonstrate
# basic operations on single array
import numpy as np
 
a = np.array([1, 2, 5, 3])
print(a)
# add 1 to every element
print ("Adding 1 to every element:", a+1)
 
# subtract 3 from each element
print ("Subtracting 3 from each element:", a-3)
 
# multiply each element by 10
print ("Multiplying each element by 10:", a*10)
 
# square each element
print ("Squaring each element:", a**2)
 
# modify existing array
a *= 2
print ("Doubled each element of original array:", a)
 
# transpose of array
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
 
print ("\nOriginal array:\n", a)
print ("Transpose of array:\n", a.T)
[1 2 5 3]
Adding 1 to every element: [2 3 6 4]
Subtracting 3 from each element: [-2 -1  2  0]
Multiplying each element by 10: [10 20 50 30]
Squaring each element: [ 1  4 25  9]
Doubled each element of original array: [ 2  4 10  6]

Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]
# Python program to demonstrate
# binary operators in Numpy
import numpy as np
 
a = np.array([[1, 2],
            [3, 4]])
b = np.array([[4, 3],
            [2, 1]])
 
# add arrays
print ("Array sum:\n", a + b)
 
# multiply arrays (elementwise multiplication)
print ("Array multiplication:\n", a*b)
 
# matrix multiplication
print ("Matrix multiplication:\n", a.dot(b))
Array sum:
 [[5 5]
 [5 5]]
Array multiplication:
 [[4 6]
 [6 4]]
Matrix multiplication:
 [[ 8  5]
 [20 13]]
# Python program to demonstrate
# universal functions in numpy
import numpy as np
 
# create an array of sine values
a = np.array([0, np.pi/2, np.pi])
print ("Sine values of array elements:", np.sin(a))
 
# exponential values
a = np.array([0, 1, 2, 3])
print ("Exponent of array elements:", np.exp(a))
 
# square root of array values
print ("Square root of array elements:", np.sqrt(a))
Sine values of array elements: [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]
Square root of array elements: [0.         1.         1.41421356 1.73205081]
# Python program to demonstrate sorting in numpy
import numpy as np
 
a = np.array([[1, 4, 2],
                 [3, 4, 6],
              [0, -1, 5]])
print(a)
# sorted array
print ("Array elements in sorted order:\n",
                    np.sort(a, axis = None))
 
# sort array row-wise
print ("Row-wise sorted array:\n",
                np.sort(a, axis = 1))
 
# specify sort algorithm
print ("Column wise sort by applying merge-sort:\n",
            np.sort(a, axis = 0, kind = 'mergesort'))
 
# Example to show sorting of structured array
# set alias names for dtypes
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)]
 
# Values to be put in array
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7),
           ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]
            
# Creating array
arr = np.array(values, dtype = dtypes)
print ("\nArray sorted by names:\n",
            np.sort(arr, order = 'name'))
             
print ("Array sorted by graduation year and then cgpa:\n",
                np.sort(arr, order = ['grad_year', 'cgpa']))
[[ 1  4  2]
 [ 3  4  6]
 [ 0 -1  5]]
Array elements in sorted order:
 [-1  0  1  2  3  4  4  5  6]
Row-wise sorted array:
 [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]
Column wise sort by applying merge-sort:
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]

Array sorted by names:
 [(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
Array sorted by graduation year and then cgpa:
 [(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]